version: "3.8"
services:
  grafana:
    image: humer/grafana
    container_name: humer-grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana/
      - /root/.humer/humer.db:/usr/share/grafana/humer.db:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
volumes:
  grafana-storage:
    driver: local
    driver_opts:
      type: none
      device: /root/.humer/grafana/
      o: bind