{
 "title": "Humer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "temperature{job=\"bathroom\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "temperature{job=\"bedroom\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "temperature{job=\"kitchen\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "temperature{job=\"livingroom\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "humidity{job=\"bathroom\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "humidity{job=\"bedroom\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "humidity{job=\"kitchen\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "humidity{job=\"livingroom\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bathroom sensor battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery{job=\"bathroom\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kitchen sensor battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery{job=\"kitchen\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bedroom sensor battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery{job=\"bedroom\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Livingroom sensor battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery{job=\"livingroom\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}