#!/usr/bin/python3

import argparse
import time
from datetime import datetime
import lywsd03mmc

parser = argparse.ArgumentParser()
parser.add_argument('mac', help='MAC address of LYWSD02 device', nargs='+')
args = parser.parse_args()

for mac in args.mac:
	try:
		client = lywsd03mmc.Lywsd03mmcClient(mac)
		data = client.data        
		print("OK,"+ str(int(time.time()))+ "," +str(mac)+ "," +str(data.temperature)+ "," +str(data.humidity)+ "," +str(data.battery))

	except Exception as e:
		print("ERROR," +str(e))
